_wandb:
    value:
        cli_version: 0.23.0
        e:
            c7c06sg1oikdo7g9bdvb450ldl0iqovm:
                codePath: steps/02_train_model.py
                codePathLocal: steps/02_train_model.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1081101176832"
                        used: "67778637824"
                executable: /home/matheus/Documents/PFP-IA-Engineering/.venv/bin/python
                git:
                    commit: 69393623ce45e0ee5a0d1f11b84723a52867339f
                    remote: git@github.com:MatheusLevy/PFP-IA-Engineering.git
                gpu: NVIDIA GeForce RTX 3070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070
                      uuid: GPU-b349ee67-4489-accd-d843-c3a927d2fe27
                host: DESKTOP-0LTH7GV
                memory:
                    total: "25200635904"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/matheus/Documents/PFP-IA-Engineering/steps/02_train_model.py
                python: CPython 3.14.0
                root: /home/matheus/Documents/PFP-IA-Engineering
                startedAt: "2025-12-03T00:24:26.003809Z"
                writerId: c7c06sg1oikdo7g9bdvb450ldl0iqovm
        m: []
        python_version: 3.14.0
        t:
            "1":
                - 1
                - 35
                - 41
                - 105
            "2":
                - 1
                - 35
                - 41
                - 105
            "3":
                - 13
                - 15
            "4": 3.14.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
amp:
    value: true
batch_size:
    value: 8
cache:
    value: false
data:
    value: ./dataset/data_freeze.yaml
dropout:
    value: 0.0908786358473959
epochs:
    value: 10
imgsz:
    value: 256
lr0:
    value: 5.613136993481251e-05
max_workers:
    value: 11
model:
    value: yolo12s
multi_scale:
    value: false
optimizer:
    value: SGD
patience:
    value: 100
trial_number:
    value: 1
