_wandb:
    value:
        cli_version: 0.23.0
        e:
            t9qwrgk5a4j7in4oqvgga4bgl9x83be8:
                codePath: steps/02_train_model.py
                codePathLocal: steps/02_train_model.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1081101176832"
                        used: "67765379072"
                executable: /home/matheus/Documents/PFP-IA-Engineering/.venv/bin/python
                git:
                    commit: 69393623ce45e0ee5a0d1f11b84723a52867339f
                    remote: git@github.com:MatheusLevy/PFP-IA-Engineering.git
                gpu: NVIDIA GeForce RTX 3070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070
                      uuid: GPU-b349ee67-4489-accd-d843-c3a927d2fe27
                host: DESKTOP-0LTH7GV
                memory:
                    total: "25200635904"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/matheus/Documents/PFP-IA-Engineering/steps/02_train_model.py
                python: CPython 3.14.0
                root: /home/matheus/Documents/PFP-IA-Engineering
                startedAt: "2025-12-03T00:23:19.598977Z"
                writerId: t9qwrgk5a4j7in4oqvgga4bgl9x83be8
        m: []
        python_version: 3.14.0
        t:
            "1":
                - 1
                - 35
                - 105
            "2":
                - 1
                - 35
                - 41
                - 105
            "3":
                - 2
                - 13
                - 15
            "4": 3.14.0
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
amp:
    value: true
batch_size:
    value: 12
cache:
    value: false
data:
    value: ./dataset/data_freeze.yaml
dropout:
    value: 0.44713734167944486
epochs:
    value: 10
imgsz:
    value: 512
lr0:
    value: 4.3297641546726356e-05
max_workers:
    value: 11
model:
    value: yolo12n
multi_scale:
    value: true
optimizer:
    value: AdamW
patience:
    value: 100
trial_number:
    value: 0
